version: "3.8"

services:
  app:
    build : .
    image: gabivoiq/isi-arcgis-project:latest
    container_name: app
    ports:
      - "${API_EXPOSED_PORT:-8081}:8081"
    networks:
      - network_api_db
    depends_on:
      - db
    environment:
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB:-arcgis}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER:-postgres}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASS:-postgres}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${JPA_DDL_AUTO:-update}
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=${LOGGING_LEVEL_SPRING:-INFO}
      - LOGGING_LEVEL_ORG_HIBERNATE=${LOGGING_LEVEL_HIBERNATE:-INFO}

  db:
    image: postgres:13.1
    ports:
      - "${DB_EXPOSED_PORT:-5432}:5432"
    container_name: db
    networks:
      - network_api_db
      - network_pg_db
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-arcgis}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASS:-postgres}
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:4.29
    ports:
      - "${PGADMIN_EXPOSED_PORT:-5000}:80"
    container_name: pgadmin
    networks:
      - network_pg_db
    environment:
      - PGADMIN_LISTEN_PORT=80
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_USERNAME:-admin@domain.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-admin}
    volumes:
      - pg_data:/var/lib/pgadmin

volumes:
  db_data:
    name: postgres_storage
  pg_data:
    name: pgadmin_storage

networks:
  network_api_db:
  network_pg_db:
